server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:hotel.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
  security:
    user:
      name: admin
      password: hotel123
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      continue-on-error: true

logging:
  level:
    com.hotel.server: INFO          # Твои классы
    org.springframework.web: DEBUG    # HTTP запросы
    org.springframework.security: INFO # Авторизация
  pattern:
    console "%d{HH:mm:ss} %-5level [%c{1}] - %msg%n"