server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:hotel.db
    driver-class-name: org.sqlite.JDBC
  security:
    user:
      name: admin
      password: hotel123
  sql:
    init:
      mode: always
      #schema-locations: classpath:schema.sql

logging:
  level:
    com.hotel.server: DEBUG
    org.springframework.web: DEBUG